# Generated by Django 4.1.2 on 2022-10-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=30)),
                ('note_image_url', models.URLField()),
                ('note_content', models.TextField()),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
