# Generated by Django 4.1.2 on 2022-10-30 07:27

import django.core.validators
from django.db import migrations, models
import final_exam.web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_username', models.CharField(max_length=10, validators=[final_exam.web.models.validate_min_length])),
                ('profile_email', models.EmailField(max_length=254)),
                ('profile_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('profile_password', models.CharField(max_length=30)),
                ('profile_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('profile_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
