# Generated by Django 4.1.2 on 2022-10-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_employee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior')], default='Junior', max_length=10, verbose_name='Seniority level'),
        ),
    ]
